### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vincentneo**
Updating the using part of the README file.

### CODE REVIEW

**Comment by AerisG222** [comment]
Thanks for the PR!

As a small improvement, could you mark the method async, and add an await on the list assignment?

If you don't have time, that's fine, I'll merge and update afterwards.  As a quick heads-up, I haven't done this yet in GH, but will try my best to make sure your contribution is attributed to you.

Thanks again!

**Comment by vincentneo** [comment]
Alright! I assume that is the improvement needed, right? 
:)

**Comment by vincentneo** [comment]
Otherwise, I feel that the entire thing can be revamped a bit more, to show more in-depth examples directly there, such that it is easier for absolute beginners to use.

Once I have the time to familiarise with this, maybe I can help a little, if you don't mind? :)

**Comment by vincentneo** [comment]
Oops... Seems I'm not up to the job. Sorry for the mistakes!

**Comment by AerisG222** [comment]
No problem, I'm fumbling around to figure out how best to merge - thanks for bearing with me as I try this for the first time =D.

Hope you are finding the library useful, if you have improvements, I would love the help!

Thanks,
Mike

**Comment by vincentneo** [comment]
Sure! 
I always liked attempting to help in other's GitHub projects, as it seems like a great and fun way to learn programming.

**Pull request merged**
